config/routes.rb
Educrasy::Application.routes.draw do
  resources :class_details

  get "teacher_lesson/add"
  get "teacher_lesson/remove"

  resources :roles

  get "admin_users/new"

  resources :developers

  resources :admin_people

  resources :choices
  resources :quests

  get "lesson_pages_questionnaire/index"

  get "lesson_pages_questionnaire/edit"

  get "lesson_pages_questionnaire/new"

  resources :content_infos

  resources :lessons

  resources :supports, :only => [:new, :create]

  get "contact/index"

  get "compleated/index"

  get "student_lesson_page/index"
  get "student_lesson_page/find"
  get "student_lesson_page/result"
  get "student_lesson_page/add"
  get "student_lesson_page/remove"
  get "student_lesson_page/lesson"
  get "student_lesson_page/nextlesson"
  get "student_lesson_page/prevlesson"
  get "student_lesson_page/teacherlesson"
  get "student_lesson_page/answers"
  get "student_lesson_page/performance"

  resources :student_details

  get "class_performance_page/index"

  get "teacher_lesson_details/index"
  get "teacher_lesson_details/add"
  get "teacher_lesson_details/remove"

  resources :teacher_details

  resources :questionnaires

  resources :lesson_pages

  resources :content_developers

  resources :students

  resources :teachers

  resources :administrators

  resources :homes

  devise_for :users
  devise_for :users
  resources :users, :has_one => :role
  resources :users do
       resources :role
  end
 resources :users do
       resources :role
  end
  resources :quests do
       resources :choices
  end

   root :to => "homes#index"

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :quest
  #validates_uniqueness_of :quest_id,:scope => [:answer]
  #validates_uniqueness_of :quest_id => [:ChoiceAnswers]
 #accepts_nested_attributes_for :quest

 end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  # GET /choices
  # GET /choices.xml
  def index
    #@choices = Choice.all
    @choice=Choice.find(:first,:conditions=>{:quest_id=>params[:id]})
    @choices = Choice.find(:all,:conditions=>{:quest_id=>params[:id]})
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @choices }
    end
  end

  # GET /choices/1
  # GET /choices/1.xml
  def show
    @choice = Choice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @choice }
    end
  end

  # GET /choices/new
  # GET /choices/new.xml
  def new
    @choice = Choice.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @choice }
    end
  end

  # GET /choices/1/edit
  def edit
    @choice = Choice.find(params[:id])
  end

  # POST /choices
  # POST /choices.xml
  def create
    @choice = Choice.new(params[:choice])

    respond_to do |format|
      if @choice.save
        flash[:notice]="Choice answer #{@choice.ChoiceAnswers} for question #{@choice.quest.question} created"
        format.html { redirect_to(:controller =>"questionnaires",:action =>"new") }
        #format.html { redirect_to(@choice, :notice => 'Choice was successfully created.') }
        format.xml  { render :xml => @choice, :status => :created, :location => @choice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /choices/1
  # PUT /choices/1.xml
  def update
    @choice = Choice.find(params[:id])

    respond_to do |format|
      if @choice.update_attributes(params[:choice])
        #format.html { redirect_to(@choice, :notice => 'Choice was successfully updated.') }
        format.html { redirect_to(:action=>"show",:controller=>"questionnaires",:id=>"#{@choice.quest.questionnaire.id}") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @choice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.xml
  def destroy
    @choice = Choice.find(params[:id])
    @choice.destroy

    respond_to do |format|
      #format.html { redirect_to(choices_url) }
      format.html { redirect_to(:action=>"show",:controller=>"questionnaires",:id=>"#{@choice.quest.questionnaire.id}") }
      format.xml  { head :ok }
    end
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_choice.html.erb
<%= fields_for "quest[choices_attributes][]", choice do |i| %>
  <li>
    <%= link_to("Remove", "#delete", :class => "delete-choice") %>
    <%= i.label :ChoiceAnswers, "Full Name" %>
    <%= i.text_field :ChoiceAnswers %>
    <%#= i.label :email, "Email Address" %>
    <%#= i.text_field :email %>
  </li>
<% end %>

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Select Question" %><br />
    <%= f.select(:quest_id, Quest.find(:all).collect {|c| [ c.question, c.id ] })%>
  </div>
  <div class="field">
    <%= f.label "Enter choice Answers" %><br />
    <%= f.text_field :ChoiceAnswers %>
  </div>
 <div class="field">
    <%= f.label "Tick Correct Answer" %>&nbsp;
    <%= f.check_box :answer %>
  </div>
   <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render 'form' %>

<%#= link_to 'Show', @choice %>
<%#= link_to 'Back', choices_path %>
<%=link_button_to 'Question Details',url_for(:action=>"show",:controller=>"questionnaires",:id=>"#{@choice.quest.questionnaire.id}") %>
<%=link_button_to 'List Choices',url_for(:action=>"index",:controller=>"choices",:id=>"#{@choice.quest_id}") %>

app/views/choices/index.html.erb
<h2>Listing  answers for question <%= @choice.quest.question  %> </h2>


<table>
  <tr>
    <th>Choice Answers</th>
    <th></th>
  </tr>

<% @choices.each do |choice| %>
  <tr>
    <td>
        <%  if choice.answer %>
        <span id="correctAnswer">
          <%= choice.ChoiceAnswers %>
        </span>
        <% else %>
        <%= choice.ChoiceAnswers %>
        <% end%>
    </td>
    <td><%= link_to 'Destroy', choice, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Choice', new_choice_path %>
<%=link_button_to "Create New Choice",url_for(:action=>"new",:controller=>"questionnaires")%>
<%=link_button_to "Back",url_for(:back)%>

app/views/choices/new.html.erb
<%= render 'choices/form' %>


<%#=link_to "Back to Adding Question",{:action=>"new", :controller=>"quests"} %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <b>Choiceanswers:</b>
  <%= @choice.ChoiceAnswers %>
</p>


<%= link_to 'Edit', edit_choice_path(@choice) %> <br />

<%=link_to " Back to adding Choice Answers",{:action=>"new", :controller=>"choices"} %>