config/routes.rb
Educrasy::Application.routes.draw do
  resources :class_details

  get "teacher_lesson/add"
  get "teacher_lesson/remove"

  resources :roles

  get "admin_users/new"

  resources :developers

  resources :admin_people

  resources :choices
  resources :quests

  get "lesson_pages_questionnaire/index"

  get "lesson_pages_questionnaire/edit"

  get "lesson_pages_questionnaire/new"

  resources :content_infos

  resources :lessons

  resources :supports, :only => [:new, :create]

  get "contact/index"

  get "compleated/index"

  get "student_lesson_page/index"
  get "student_lesson_page/find"
  get "student_lesson_page/result"
  get "student_lesson_page/add"
  get "student_lesson_page/remove"
  get "student_lesson_page/lesson"
  get "student_lesson_page/nextlesson"
  get "student_lesson_page/prevlesson"
  get "student_lesson_page/teacherlesson"
  get "student_lesson_page/answers"
  get "student_lesson_page/performance"

  resources :student_details

  get "class_performance_page/index"

  get "teacher_lesson_details/index"
  get "teacher_lesson_details/add"
  get "teacher_lesson_details/remove"

  resources :teacher_details

  resources :questionnaires

  resources :lesson_pages

  resources :content_developers

  resources :students

  resources :teachers

  resources :administrators

  resources :homes

  devise_for :users
  devise_for :users
  resources :users, :has_one => :role
  resources :users do
       resources :role
  end
 resources :users do
       resources :role
  end
  resources :quests do
       resources :choices
  end

   root :to => "homes#index"

end

app/models/student_detail.rb
class StudentDetail < ActiveRecord::Base
  belongs_to :class_detail
  belongs_to :user
end

app/controllers/student_details_controller.rb
class StudentDetailsController < ApplicationController
  # GET /student_details
  # GET /student_details.xml
  def index
    @student_details = StudentDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @student_details }
    end
  end

  # GET /student_details/1
  # GET /student_details/1.xml
  def show
    @student_detail = StudentDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student_detail }
    end
  end

  # GET /student_details/new
  # GET /student_details/new.xml
  def new
    @student_detail = StudentDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student_detail }
    end
  end

  # GET /student_details/1/edit
  def edit
    @student_detail = StudentDetail.find(params[:id])
  end

  # POST /student_details
  # POST /student_details.xml
  def create
    @student_detail = StudentDetail.new(params[:student_detail])

    respond_to do |format|
      if @student_detail.save
        #format.html { redirect_to(@student_detail, :notice => 'Student detail was successfully created.') }
        flash[:notice]="Student #{@student_detail.user.name} assigned to class #{@student_detail.class_detail.classname}"
        format.html { redirect_to(:controller =>"admin_people",:action =>"index") }
        format.xml  { render :xml => @student_detail, :status => :created, :location => @student_detail }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /student_details/1
  # PUT /student_details/1.xml
  def update
    @student_detail = StudentDetail.find(params[:id])

    respond_to do |format|
      if @student_detail.update_attributes(params[:student_detail])
        #format.html { redirect_to(@student_detail, :notice => 'Student detail was successfully updated.') }
        format.html { redirect_to(:action=>"index", :controller=>"student_details") }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student_detail.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /student_details/1
  # DELETE /student_details/1.xml
  def destroy
    @student_detail = StudentDetail.find(params[:id])
    @student_detail.destroy

    respond_to do |format|
      format.html { redirect_to(student_details_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/student_details_helper.rb
module StudentDetailsHelper
end

app/views/student_details/_form.html.erb
<%  @student_detail = StudentDetail.new %>
<%= form_for(@student_detail) do |f| %>
  <% if @student_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_detail.errors.count, "error") %> prohibited this student_detail from being saved:</h2>

      <ul>
      <% @student_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<span class="field">
    <%= f.label "Student" %>&nbsp;&nbsp;
    <%= f.select(:user_id, Role.where(:name=>"student").collect {|c| [ c.user.name, c.id ] })%>
  </span>&nbsp;&nbsp;
<span class="field">
    <%= f.label "Class" %> &nbsp;&nbsp;
    <%= f.select(:class_detail_id, ClassDetail.find(:all).collect {|c| [ c.classname, c.id ] })%>
  </span>

&nbsp;&nbsp;
  <span class="actions">
    <%= f.submit "Assign"%>
  </span>
<% end %>

app/views/student_details/edit.html.erb
<h1>Edit Student Class Information</h1>

<%= render 'form' %>

<%#= link_to 'Show', @student_detail %>
<%= link_button_to "Back to List Page", url_for(:action=>"index", :controller=>"student_details")%>

app/views/student_details/index.html.erb
<h1>Listing Student Class Details</h1>
<table>
  <tr>
    <th>Studen Name</th>
    <th>Class Name</th>
    <th></th>
    <th></th>
  </tr>
<% @student_details.each do |student_detail| %>
  <tr>
    <td><%= student_detail.user.name %></td>
    <td><%= student_detail.class_detail.classname %></td>
    <td><%= link_to 'Edit', edit_student_detail_path(student_detail) %></td>
    <td><%= link_to 'Destroy', student_detail, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_button_to "Back to Admin page", url_for(:action=>"index", :controller=>"admin_people")%>

app/views/student_details/new.html.erb
<%= render 'student_details/form' %>

<%#= link_to 'Back', student_details_path %>

app/views/student_details/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_student_detail_path(@student_detail) %> |
<%= link_to 'Back', student_details_path %>