config/routes.rb
Educrasy::Application.routes.draw do
  resources :class_details

  get "teacher_lesson/add"
  get "teacher_lesson/remove"

  resources :roles

  get "admin_users/new"

  resources :developers

  resources :admin_people

  resources :choices
  resources :quests

  get "lesson_pages_questionnaire/index"

  get "lesson_pages_questionnaire/edit"

  get "lesson_pages_questionnaire/new"

  resources :content_infos

  resources :lessons

  resources :supports, :only => [:new, :create]

  get "contact/index"

  get "compleated/index"

  get "student_lesson_page/index"
  get "student_lesson_page/find"
  get "student_lesson_page/result"
  get "student_lesson_page/add"
  get "student_lesson_page/remove"
  get "student_lesson_page/lesson"
  get "student_lesson_page/nextlesson"
  get "student_lesson_page/prevlesson"
  get "student_lesson_page/teacherlesson"
  get "student_lesson_page/answers"
  get "student_lesson_page/performance"

  resources :student_details

  get "class_performance_page/index"

  get "teacher_lesson_details/index"
  get "teacher_lesson_details/add"
  get "teacher_lesson_details/remove"

  resources :teacher_details

  resources :questionnaires

  resources :lesson_pages

  resources :content_developers

  resources :students

  resources :teachers

  resources :administrators

  resources :homes

  devise_for :users
  devise_for :users
  resources :users, :has_one => :role
  resources :users do
       resources :role
  end
 resources :users do
       resources :role
  end
  resources :quests do
       resources :choices
  end

   root :to => "homes#index"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_and_belongs_to_many :developers
  has_many :lesson_pages
  has_many :teacher_lessons
  has_many :lesson_classes
  has_many :student_lessons
  validates_uniqueness_of :lessonName
  validates(:lessonName, :presence => true)

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /lessons
  # GET /lessons.xml
  def index
    @lessons = Lesson.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lessons }
    end
  end

  # GET /lessons/1
  # GET /lessons/1.xml
  def show
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/new
  # GET /lessons/new.xml
  def new
    @lesson = Lesson.new
    @lesson_page = LessonPage.new
     respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lesson }
    end
  end

  # GET /lessons/1/edit
  def edit
    @lesson = Lesson.find(params[:id])
   end
  # POST /lessons
  # POST /lessons.xml
  def create
    @lesson = Lesson.new(params[:lesson])
    @lesson_page = LessonPage.new(params[:lesson_page])
    @developerslessons =DevelopersLessons.new
    @developer=Developer.new
    respond_to do |format|
      if @lesson.save
         @developer.lessonID=@lesson.id
         @developer.userid=current_user.id
         @developer.save
         @developerslessons.lesson_id=@lesson.id
         @developerslessons.developer_id=@developer.id
         @developerslessons.save
         #format.html { redirect_to(:controller =>"developers",:action =>"index") }
         flash[:notice]="Lesson Name #{@lesson.lessonName} Created"
         format.html { redirect_to(:controller =>"lessons",:action =>"new") }
         format.xml  { render :xml => @lesson, :status => :created, :location => @lesson }
       else
        format.html{ render :action => "new"}
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end
  # PUT /lessons/1
  # PUT /lessons/1.xml
  def update
    @lesson = Lesson.find(params[:id])
    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to(@lesson, :notice => 'Lesson was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lesson.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.xml
  def destroy
    @lesson = Lesson.find(params[:id])
    @developers=Developer.find(:all,:conditions=>{:lessonID=>@lesson.id})
    @developers.each do | developer |
      developer.destroy
    end
    @developerslessons =DevelopersLessons.find(:all,:conditions=>{:lesson_id=>@lesson.id})
    @developerslessons.each do | deve |
      deve.destroy
    end

    @lesson_page = LessonPage.find(:all,:conditions=>{:lesson_id=>@lesson.id})
    @lesson_page.each do |less |
      less.destroy
    end
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to(lessons_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_for(@lesson) do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   
  <span class="field">
    <%= f.label "Enter Lesson Name" %><br />
    <%= f.text_field :lessonName %>
  </span>
  <span class="actions">
    <%= f.submit "Create Lesson Name" %>
  </span>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing lesson</h1>

<%= render 'form' %>
<br />
<%#= link_to 'Show', @lesson %>
<%#= link_to 'Back', lessons_path %>
<%#= link_button_to "Show", url_for(@lesson)%> &nbsp; &nbsp;
<%= link_button_to "Back", url_for(:back)%>

app/views/lessons/index.html.erb
<h1>Listing lesson names</h1>

<table>
  <tr>
    
    <th>Lessonname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lessons.each do |lesson| %>
  <tr>
    
    <td><%= lesson.lessonName %></td>
    <td><%= link_to 'Show', lesson %></td>
    <td><%= link_to 'Edit', edit_lesson_path(lesson) %></td>
    <td><%= link_to 'Destroy', lesson, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />


<%#= link_to 'New Lesson', new_lesson_path %>
<%= link_button_to "Create New Lesson", url_for(new_lesson_path)%> &nbsp; &nbsp;
<%= link_button_to "Lesson Details", url_for(:action=>"index",:controller=>"developers")%>

app/views/lessons/new.html.erb
<div class="span-25 last">
  <h1>Create New lesson</h1>
</div>
 <div class="span-25 last lessonBorder">
    <%= render 'form' %>
 </div>
<div class="span-13">
  <br />
  <h3> Add Content data</h3>
  <div class="lessonBorder">
    <%=render :template=>'lesson_pages/new'%>
  </div>
</div>
<div class="span-12 last">
  <br />
  <h3> Add Questionnaire data</h3>
  <div class="lessonBorder">
    <%=render :template=>'lesson_pages_questionnaire/new'%>
   </div>
</div>
<div class="span-25 last">
<%= link_button_to "Create New Content", url_for(:action=>"new", :controller=>"content_infos")%> &nbsp; &nbsp;
<%=link_button_to "Create Questionnire",url_for(:action=>"new", :controller=>"questionnaires") %>&nbsp; &nbsp;
<%=link_button_to "Lesson Details page",url_for(:action=>"index", :controller=>"developers") %>
</div>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Lesson Name:</b>
  <%= @lesson.lessonName %>
</p>


<%#= link_to 'Edit', edit_lesson_path(@lesson) %>
<%#=link_to "Back",{:action=>"new", :controller=>"lessons"} %>

<%= link_button_to "Edit", url_for(edit_lesson_path(@lesson))%> &nbsp; &nbsp;
<%= link_button_to "Lesson Details", url_for(:action=>"index",:controller=>"developers")%>&nbsp; &nbsp;
<%= link_button_to "Lesson Name List", url_for(:action=>"index",:controller=>"lessons")%>