config/routes.rb
Educrasy::Application.routes.draw do
  resources :class_details

  get "teacher_lesson/add"
  get "teacher_lesson/remove"

  resources :roles

  get "admin_users/new"

  resources :developers

  resources :admin_people

  resources :choices
  resources :quests

  get "lesson_pages_questionnaire/index"

  get "lesson_pages_questionnaire/edit"

  get "lesson_pages_questionnaire/new"

  resources :content_infos

  resources :lessons

  resources :supports, :only => [:new, :create]

  get "contact/index"

  get "compleated/index"

  get "student_lesson_page/index"
  get "student_lesson_page/find"
  get "student_lesson_page/result"
  get "student_lesson_page/add"
  get "student_lesson_page/remove"
  get "student_lesson_page/lesson"
  get "student_lesson_page/nextlesson"
  get "student_lesson_page/prevlesson"
  get "student_lesson_page/teacherlesson"
  get "student_lesson_page/answers"
  get "student_lesson_page/performance"

  resources :student_details

  get "class_performance_page/index"

  get "teacher_lesson_details/index"
  get "teacher_lesson_details/add"
  get "teacher_lesson_details/remove"

  resources :teacher_details

  resources :questionnaires

  resources :lesson_pages

  resources :content_developers

  resources :students

  resources :teachers

  resources :administrators

  resources :homes

  devise_for :users
  devise_for :users
  resources :users, :has_one => :role
  resources :users do
       resources :role
  end
 resources :users do
       resources :role
  end
  resources :quests do
       resources :choices
  end

   root :to => "homes#index"

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource :except=> 'index'
  # GET /teachers
  # GET /teachers.xml
  def index
    @teachers = Teacher.all
    if current_user.role.name=='teacher'
    redirect_to(:controller => "teacher_details",:action => "index")
    return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.xml
  def show
    #@teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.xml
  def new
    #@teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    #@teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.xml
  def create
    #@teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully created.') }
        format.xml  { render :xml => @teacher, :status => :created, :location => @teacher }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.xml
  def update
    #@teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.xml
  def destroy
    #@teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to(teachers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lessionID %><br />
    <%= f.text_field :lessionID %>
  </div>
  <div class="field">
    <%= f.label :classname %><br />
    <%= f.text_field :classname %>
  </div>
  <div class="field">
    <%= f.label :classID %><br />
    <%= f.text_field :classID %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
  <div class="span-25 last" id="header">
    Teachers
  </div>
  <div class="span-15" id="header2">
    Educrasy <br />
    Education for 21 century
   </div>
   <div class="textsize span-10 last" id="logo">
     logo

   </div>
   <div class="textsize span-25 last" >
    I am a
    </div>
    <div class="span-25 last" id="mainlinks">
      <%=link_to "Administrator",{:action=>"index", :controller=>"administrators"} %>
      <%=link_to "Content Developer",{:action=>"index", :controller=>"content_developers"} %>
      <%=link_to "Student",{:action=>"index", :controller=>"students"} %>
    </div>
    <div class=" textsize span-25 last">
    <!--Who we are-->
    </div>
    <div class="span-10" id="video">
    Teachers
    </div>
    <div class="textsize span-14 last" id="signup">
      <% if !user_signed_in? %>
      <%=  link_to "Sign up",new_user_registration_path %> or <%= link_to "Sign_in", new_user_session_path %>

      <% end %> <br />
      <div id="contact">
          <%=link_to "Contact",{:action=>"new", :controller=>"supports"} %>
      </div>

    </div>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lessionid:</b>
  <%= @teacher.lessionID %>
</p>

<p>
  <b>Classname:</b>
  <%= @teacher.classname %>
</p>

<p>
  <b>Classid:</b>
  <%= @teacher.classID %>
</p>


<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>